name: flutter_static_html_wrapper
description: A Flutter project to run html games / websites on mobile.

publish_to: 'none'
version: 1.0.0+0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  webview_flutter:
  local_assets_server:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # If your game / website contains folders, you need to specify them like this:
  # assets:
  #   - assets/
  #   - assets/folder1/
  #   - assets/folder2/

  assets:
    - assets/
